language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

stages:
  - name: build
    if: (NOT branch = master) AND (tag IS blank)
  - name: release
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    # run integration test and maven build
    - stage: build
      script:
        - docker-compose up -d
        - mvn clean install

    # release a version
    - stage: release
      script:
        - mvn clean install -DskipTests
      before_deploy:
        if ! [[ $TAG ]]; then
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) &&
          export TAG="v$VERSION" &&
          git config --global user.name "Travis CI" &&
          git config --global user.email "builds@travis-ci.com" &&
          git tag $TAG;
        fi
      deploy:
        - provider: bintray
          file: "bintray.json"
          user: $BINTRAY_USER
          key: $BINTRAY_API_KEY
          skip_cleanup: true
        - provider: releases
          api_key:
            secure: $GITHUB_OAUTH_TOKEN
          body: "Please take a look into the [changelog](https://github.com/kryptokrauts/contraect-maven-plugin/blob/${TAG}/docs/changelog.md) for more information about the recent changes."
          skip_cleanup: true
          file_glob: true
          file:
            - target/*.jar