name: Pull Request

on:
  pull_request:
    branches-ignore: [ 'main' ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set Environment Variables
        run: |
          echo "AETERNITY_BASE_URL=http://localhost" >> $GITHUB_ENV
          echo "COMPILER_BASE_URL=http://localhost:3080" >> $GITHUB_ENV
      - name: Test & Build
        run: |
          docker-compose up -d
          mvn clean package